### ISSUE TITLE
Can we make this work with another bot?

### ISSUE THREAD

**Issue by paperc07** [luke-nigro/red-skull-bot#1]
I am not sure what we could or if we could but just curious

**Comment by luke-nigro** [comment]
Can you be more specific as to what you're trying to make work with another bot?

**Comment by paperc07** [comment]
I honestly dont know we are all trying to use this one https://github.com/AdriaGual/marvel-snap-bot 

but I see yours pulls images and what not so wondering if there was anyway to integrate it but I don't think there is

**Comment by luke-nigro** [comment]
You mean an easy way to pulls images? I link to marvelsnapzone's images and am just manually updating as cards are changed/added since its a pretty slow drip and manageable. I initially loaded the list of links from a random Kaggle dataset I found.

**Comment by paperc07** [comment]
oh ok I pull all my images from here and i've changed the code to where it pulls all the cards and locations using this guys stuff 
https://github.com/vlmaier/marvel-snap-scrapr

But yeah so we tried to pull all the images thinking like ok well these are the actual game images. So we figured ok now that we have that we should be able to link the bot to see the images we got and identify them in the bot, but it just wasn't the case so we have to literally use a function to screen shot the cards and then take snips of the images and add them to a folder and if you put a few in there it will recognize one of them. 

Trust me I thought it was going to be simple download all the images and the bot would be able to read it but of course life is always difficult, nothings ever easy
